# Generated by Django 4.2.10 on 2024-03-09 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamLeader",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="newuser",
            name="otp_expire",
        ),
        migrations.RemoveField(
            model_name="newuser",
            name="reservation_count",
        ),
        migrations.AlterField(
            model_name="newuser",
            name="otp",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="otp code"
            ),
        ),
        migrations.AlterField(
            model_name="newuser",
            name="phone_number",
            field=models.CharField(verbose_name="phone number"),
        ),
        migrations.CreateModel(
            name="TeamMembers",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_members_leader",
                        to="accounts.teamleader",
                        verbose_name="choose leader",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="team_members_users",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="choose user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="teamleader",
            name="leader",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_leader_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Leader",
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("body", models.TextField(verbose_name="comment text")),
                (
                    "status",
                    models.BooleanField(default=False, verbose_name="comment display"),
                ),
                (
                    "rate",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "one"),
                            (2, "two"),
                            (3, "three"),
                            (4, "four"),
                            (5, "five"),
                        ],
                        default=5,
                        verbose_name="select rate",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_author_id",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="comment author",
                    ),
                ),
            ],
        ),
    ]
