# Generated by Django 4.2.10 on 2024-03-09 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0002_calendar_is_active_alter_calendar_day_and_more"),
        ("accounts", "0002_teamleader_remove_newuser_otp_expire_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_room_id",
                to="reservation.room",
                verbose_name="select room",
            ),
        ),
    ]
