# Generated by Django 4.2.10 on 2024-03-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_newuser_otp_expire"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_images",
                verbose_name="change avatar",
            ),
        ),
    ]
