# Generated by Django 4.2.10 on 2024-03-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_newuser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="6596121.png",
                null=True,
                upload_to="profile_images",
                verbose_name="change avatar",
            ),
        ),
    ]
