# Generated by Django 4.2.10 on 2024-03-09 07:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_newuser_otp"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTPCode",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(unique=True, verbose_name="phone number"),
                ),
                ("otp", models.PositiveBigIntegerField(verbose_name="otp code")),
            ],
        ),
        migrations.RemoveField(
            model_name="newuser",
            name="otp",
        ),
        migrations.RemoveField(
            model_name="newuser",
            name="otp_expire",
        ),
        migrations.RemoveField(
            model_name="newuser",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="newuser",
            name="reservation_count",
        ),
    ]
