# Generated by Django 4.2.10 on 2024-03-09 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0013_alter_calendar_day"),
        (
            "accounts",
            "0007_otpcode_remove_newuser_otp_remove_newuser_otp_expire_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otpcode",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="newuser",
            name="phone_number",
            field=models.CharField(
                default="", unique=True, verbose_name="phone number"
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="TeamLeader",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "leader",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_leader_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Leader",
                    ),
                ),
                (
                    "users",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users_of_team",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("body", models.TextField(verbose_name="comment text")),
                (
                    "status",
                    models.BooleanField(default=False, verbose_name="comment display"),
                ),
                (
                    "rate",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "one"),
                            (2, "two"),
                            (3, "three"),
                            (4, "four"),
                            (5, "five"),
                        ],
                        default=5,
                        verbose_name="select rate",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_author_id",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="comment author",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_room_id",
                        to="reservation.room",
                        verbose_name="select room",
                    ),
                ),
            ],
        ),
    ]
