# Generated by Django 4.2.10 on 2024-03-09 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_delete_otpcode_newuser_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamleader",
            name="users",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users_of_team",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
