# Generated by Django 4.2.10 on 2024-03-09 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_teamleader_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teamleader",
            name="users",
        ),
        migrations.CreateModel(
            name="TeamMembers",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "leader",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_members_leader",
                        to="accounts.teamleader",
                        verbose_name="choose leader",
                    ),
                ),
                (
                    "users",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_members_users",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="choose user",
                    ),
                ),
            ],
        ),
    ]
