# Generated by Django 4.2.10 on 2024-03-04 13:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Calendar",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("day", models.SmallIntegerField(verbose_name="choose day")),
                (
                    "start_time",
                    models.CharField(max_length=256, verbose_name="start time"),
                ),
                ("end_time", models.CharField(max_length=256, verbose_name="end time")),
                ("date", models.DateField(verbose_name="choose date")),
            ],
        ),
    ]
