# Generated by Django 4.2.10 on 2024-03-09 16:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_teamleader_remove_newuser_otp_expire_and_more"),
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendar",
            name="is_active",
            field=models.BooleanField(
                default=True, verbose_name="this time active or no"
            ),
        ),
        migrations.AlterField(
            model_name="calendar",
            name="day",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "saturday"),
                    (1, "sunday"),
                    (2, "monday"),
                    (3, "tuesday"),
                    (4, "wednesday"),
                    (5, "thursday"),
                    (6, "friday"),
                ],
                default=0,
                verbose_name="select day",
            ),
        ),
        migrations.AlterField(
            model_name="calendar",
            name="end_time",
            field=models.TimeField(verbose_name="end time"),
        ),
        migrations.AlterField(
            model_name="calendar",
            name="start_time",
            field=models.TimeField(verbose_name="start time"),
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="first room",
                        max_length=256,
                        verbose_name="title of room",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(default=False, verbose_name="status of room"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "capacity",
                    models.SmallIntegerField(default=0, verbose_name="room capacity"),
                ),
                (
                    "calendar_id",
                    models.ManyToManyField(
                        related_name="room_calendar_id",
                        to="reservation.calendar",
                        verbose_name="choose day and time",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation_leader_id",
                        to="accounts.teamleader",
                        verbose_name="choose leader",
                    ),
                ),
                (
                    "room_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation_room_id",
                        to="reservation.room",
                        verbose_name="choose room",
                    ),
                ),
            ],
        ),
    ]
