# Generated by Django 4.2.10 on 2024-03-04 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "reservation",
            "0002_alter_calendar_end_time_alter_calendar_start_time_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="title",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="title of room"
            ),
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=False, verbose_name="reservation status"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation_room_id",
                        to="reservation.room",
                        verbose_name="choose room",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation_user_id",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="choose user",
                    ),
                ),
            ],
        ),
    ]
