# Generated by Django 4.2.10 on 2024-03-04 15:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reservation", "0003_room_title_reservation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="user_id",
        ),
        migrations.AddField(
            model_name="reservation",
            name="user_id",
            field=models.ManyToManyField(
                related_name="reservation_user_id",
                to=settings.AUTH_USER_MODEL,
                verbose_name="choose user",
            ),
        ),
    ]
