# Generated by Django 4.2.10 on 2024-03-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0004_remove_reservation_user_id_reservation_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="capacity",
            field=models.SmallIntegerField(default=0, verbose_name="room capacity"),
        ),
    ]
