# Generated by Django 4.2.10 on 2024-03-05 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0005_room_capacity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="calendar_id",
        ),
        migrations.AddField(
            model_name="reservation",
            name="calendar_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservation_calendar_id",
                to="reservation.calendar",
                verbose_name="choose day and time",
            ),
        ),
    ]
