# Generated by Django 4.2.10 on 2024-03-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0007_remove_reservation_calendar_id_room_calendar_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendar",
            name="is_active",
            field=models.BooleanField(
                default=True, verbose_name="this time active or no"
            ),
        ),
    ]
