# Generated by Django 4.2.10 on 2024-03-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0009_remove_room_calendar_id_room_calendar_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="calendar_id",
            field=models.ManyToManyField(
                related_name="room_calendar_id",
                to="reservation.calendar",
                verbose_name="choose day and time",
            ),
        ),
    ]
