# Generated by Django 4.2.10 on 2024-03-06 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0010_alter_room_calendar_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="status",
        ),
    ]
