# Generated by Django 4.2.10 on 2024-03-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0011_remove_reservation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="title",
            field=models.CharField(
                default="first room", max_length=256, verbose_name="title of room"
            ),
        ),
    ]
