# Generated by Django 4.2.10 on 2024-03-09 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_delete_otpcode_newuser_otp"),
        ("reservation", "0013_alter_calendar_day"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="user_id",
        ),
        migrations.AddField(
            model_name="reservation",
            name="leader",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservation_leader_id",
                to="accounts.teamleader",
                verbose_name="choose leader",
            ),
            preserve_default=False,
        ),
    ]
